# Generated by Django 4.1.7 on 2023-04-01 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='home_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='home_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='home_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_number', models.IntegerField()),
                ('title', models.CharField(max_length=40)),
                ('city', models.CharField(choices=[('Ankara', 'Ankara'), ('Istanbul', 'Istanbul'), ('Izmir', 'Izmir'), ('Mersin', 'Mersin'), ('Aydin', 'Aydin')], max_length=40)),
                ('Type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], max_length=40)),
                ('price', models.IntegerField()),
                ('bedrooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('5+', '5+')], max_length=40)),
                ('bathrooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('5+', '5+')], max_length=40)),
                ('image', models.ImageField(upload_to='home_images')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addressName', to='home.home_address')),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.home_description')),
            ],
        ),
    ]
